
producer-consumer: producer-consumer.c
	gcc -o producer-consumer producer-consumer.c -pthread

pthread-creation: pthread-creation.c
	gcc -o pthread-creation pthread-creation.c -pthread

pthread-creation-quiz-1: pthread-creation-quiz-1.c
	gcc -o pthread-creation-quiz-1 pthread-creation-quiz-1.c -pthread

pthread-creation-quiz-2: pthread-creation-quiz-2.c
	gcc -o pthread-creation-quiz-2 pthread-creation-quiz-2.c -pthread

pthread-creation-quiz-3: pthread-creation-quiz-3.c
	gcc -o pthread-creation-quiz-3 pthread-creation-quiz-3.c -pthread

clean:
	rm producer-consumer
	rm pthread-creation
	rm pthread-creation-quiz-1
	rm pthread-creation-quiz-2
	rm pthread-creation-quiz-3
